tasks:
  - init: echo "Replace me with a build script for the project."
    command: cd sample && make test
#image: weileizeng/itpp-full:gitpod
image:
#  file: Dockerfile
  file: .gitpod.Dockerfile
#  file: Dockerfile-gitpod