tasks:
  - init: echo "Replace me with a build script for the project."
    command: cd sample && make test


image:
  file: .gitpod.Dockerfile
# one can also use a pre-build docker image to boost the loading (only for the first time), by replacing the above line by the following line
#image: weileizeng/itpp-full:gitpod